services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: india_rosa
      POSTGRES_PASSWORD: india_rosa
      POSTGRES_DB: india_rosa
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
