// Datos simulados de la fase "visual con datos simulados" (ver CLAUDE.md).
// Nadie fuera de datos/repositorioMemoria.ts debería importar este archivo
// directamente: el acceso pasa siempre por datos/repositorio.ts.

import type { Categoria, Cupon, Producto, ValorAtributo } from '../tipos/index.ts';

export const CATEGORIAS: Categoria[] = [
  { id: 'cat-pelucas', nombre: 'Pelucas', slug: 'pelucas' },
  { id: 'cat-cuidado', nombre: 'Cuidado', slug: 'cuidado' },
  { id: 'cat-extensiones', nombre: 'Extensiones', slug: 'extensiones' },
  { id: 'cat-accesorios', nombre: 'Accesorios', slug: 'accesorios' },
];

const COLORES = {
  negroNatural: { nombre: 'Negro natural', hex: '#1c1412' },
  castanoOscuro: { nombre: 'Castaño oscuro', hex: '#3b2620' },
  chocolate: { nombre: 'Chocolate', hex: '#5a3a2a' },
  caramelo: { nombre: 'Caramelo', hex: '#8a5a34' },
  miel: { nombre: 'Miel', hex: '#a97e4c' },
  rubioArena: { nombre: 'Rubio arena', hex: '#c9a97c' },
} as const satisfies Record<string, ValorAtributo>;

function imagen(slugProducto: string, indice: number, altTexto: string) {
  return {
    id: `img-${slugProducto}-${indice}`,
    url: `/productos/${slugProducto}-${indice}.jpg`,
    altTexto,
  };
}

// Todavía no hay fotos reales: cada entrada es el mismo marcador de
// posición con un desplazamiento de tono distinto, solo para poder ver y
// probar la tira de miniaturas de la ficha de producto.
function imagenesProducto(slugProducto: string, nombre: string) {
  return [
    imagen(slugProducto, 1, `${nombre}, vista principal`),
    imagen(slugProducto, 2, `${nombre}, tono más claro`),
    imagen(slugProducto, 3, `${nombre}, tono más oscuro`),
    imagen(slugProducto, 4, `${nombre}, tono intenso`),
  ];
}

export const PRODUCTOS: Producto[] = [
  // --- Pelucas: máximo 4 variantes, combinaciones distintas entre productos ---
  {
    id: 'prod-peluca-lace-front-valentina',
    nombre: 'Peluca Lace Front Valentina',
    slug: 'peluca-lace-front-valentina',
    descripcion:
      'Peluca de lace front con encaje transparente en la línea frontal, cabello 100% humano remy.',
    categoriaId: 'cat-pelucas',
    precioBase: 420000,
    precioAntes: 480000,
    calificacion: 4.7,
    cantidadResenas: 128,
    destacado: true,
    imagenes: imagenesProducto('peluca-lace-front-valentina', 'Peluca Lace Front Valentina'),
    variantes: [
      {
        id: 'var-PLV-NEG-130',
        sku: 'PLV-NEG-130',
        precio: 420000,
        stockActual: 14,
        stockReservado: 2,
        tipoBase: 'Lace front',
        longitud: 'Larga',
        talla: 'Mediana',
        densidad: '130%',
        color: COLORES.negroNatural,
      },
      {
        id: 'var-PLV-CAS-150',
        sku: 'PLV-CAS-150',
        precio: 440000,
        stockActual: 9,
        stockReservado: 1,
        tipoBase: 'Lace front',
        longitud: 'Larga',
        talla: 'Mediana',
        densidad: '150%',
        color: COLORES.castanoOscuro,
      },
      {
        id: 'var-PLV-CHO-150',
        sku: 'PLV-CHO-150',
        precio: 440000,
        stockActual: 6,
        stockReservado: 0,
        tipoBase: 'Lace front',
        longitud: 'Larga',
        talla: 'Mediana',
        densidad: '150%',
        color: COLORES.chocolate,
      },
      {
        // Variante agotada, para probar el estado "sin stock" en el catálogo.
        id: 'var-PLV-CAR-180',
        sku: 'PLV-CAR-180',
        precio: 465000,
        stockActual: 0,
        stockReservado: 0,
        tipoBase: 'Lace front',
        longitud: 'Larga',
        talla: 'Mediana',
        densidad: '180%',
        color: COLORES.caramelo,
      },
    ],
  },
  {
    id: 'prod-peluca-full-lace-camila',
    nombre: 'Peluca Full Lace Camila',
    slug: 'peluca-full-lace-camila',
    descripcion:
      'Peluca full lace con encaje en toda la base, permite peinados hacia atrás y raya en cualquier dirección.',
    categoriaId: 'cat-pelucas',
    precioBase: 520000,
    calificacion: 4.8,
    cantidadResenas: 76,
    destacado: true,
    imagenes: imagenesProducto('peluca-full-lace-camila', 'Peluca Full Lace Camila'),
    variantes: [
      {
        id: 'var-PFC-MED-MIEL',
        sku: 'PFC-MED-MIEL',
        precio: 520000,
        stockActual: 8,
        stockReservado: 1,
        tipoBase: 'Full lace',
        longitud: 'Media',
        talla: 'Grande',
        densidad: '150%',
        color: COLORES.miel,
      },
      {
        id: 'var-PFC-LAR-RUB',
        sku: 'PFC-LAR-RUB',
        precio: 545000,
        stockActual: 5,
        stockReservado: 0,
        tipoBase: 'Full lace',
        longitud: 'Larga',
        talla: 'Grande',
        densidad: '150%',
        color: COLORES.rubioArena,
      },
      {
        id: 'var-PFC-EXL-NEG',
        sku: 'PFC-EXL-NEG',
        precio: 570000,
        stockActual: 3,
        stockReservado: 1,
        tipoBase: 'Full lace',
        longitud: 'Extra larga',
        talla: 'Grande',
        densidad: '150%',
        color: COLORES.negroNatural,
      },
    ],
  },
  {
    id: 'prod-peluca-bob-cleo',
    nombre: 'Peluca Bob Cleo',
    slug: 'peluca-bob-cleo',
    descripcion:
      'Peluca corte bob a la altura de la mandíbula, base de monofilamento para un nacimiento natural.',
    categoriaId: 'cat-pelucas',
    precioBase: 310000,
    calificacion: 4.5,
    cantidadResenas: 54,
    destacado: false,
    imagenes: imagenesProducto('peluca-bob-cleo', 'Peluca Bob Cleo'),
    variantes: [
      {
        id: 'var-PBC-PEQ-CAS',
        sku: 'PBC-PEQ-CAS',
        precio: 310000,
        stockActual: 11,
        stockReservado: 0,
        tipoBase: 'Monofilamento',
        longitud: 'Corta',
        talla: 'Pequeña',
        densidad: '130%',
        color: COLORES.castanoOscuro,
      },
      {
        id: 'var-PBC-MED-CHO',
        sku: 'PBC-MED-CHO',
        precio: 310000,
        stockActual: 7,
        stockReservado: 2,
        tipoBase: 'Monofilamento',
        longitud: 'Corta',
        talla: 'Mediana',
        densidad: '130%',
        color: COLORES.chocolate,
      },
      {
        id: 'var-PBC-MED-NEG',
        sku: 'PBC-MED-NEG',
        precio: 310000,
        stockActual: 10,
        stockReservado: 0,
        tipoBase: 'Monofilamento',
        longitud: 'Corta',
        talla: 'Mediana',
        densidad: '130%',
        color: COLORES.negroNatural,
      },
    ],
  },
  {
    id: 'prod-peluca-ondulada-renata',
    nombre: 'Peluca Ondulada Renata',
    slug: 'peluca-ondulada-renata',
    descripcion: 'Peluca de ondas suaves, base tradicional cosida, ideal para uso diario.',
    categoriaId: 'cat-pelucas',
    precioBase: 265000,
    calificacion: 4.3,
    cantidadResenas: 41,
    destacado: false,
    imagenes: imagenesProducto('peluca-ondulada-renata', 'Peluca Ondulada Renata'),
    variantes: [
      {
        id: 'var-POR-D130',
        sku: 'POR-D130',
        precio: 265000,
        stockActual: 13,
        stockReservado: 0,
        tipoBase: 'Tradicional',
        longitud: 'Media',
        talla: 'Mediana',
        densidad: '130%',
        color: COLORES.caramelo,
      },
      {
        id: 'var-POR-D150',
        sku: 'POR-D150',
        precio: 280000,
        stockActual: 9,
        stockReservado: 1,
        tipoBase: 'Tradicional',
        longitud: 'Media',
        talla: 'Mediana',
        densidad: '150%',
        color: COLORES.caramelo,
      },
      {
        id: 'var-POR-D180',
        sku: 'POR-D180',
        precio: 300000,
        stockActual: 4,
        stockReservado: 0,
        tipoBase: 'Tradicional',
        longitud: 'Media',
        talla: 'Mediana',
        densidad: '180%',
        color: COLORES.caramelo,
      },
    ],
  },
  {
    id: 'prod-peluca-rizada-solange',
    nombre: 'Peluca Rizada Solange',
    slug: 'peluca-rizada-solange',
    descripcion:
      'Peluca de rizos definidos, densidad alta y encaje lace front para un look voluminoso.',
    categoriaId: 'cat-pelucas',
    precioBase: 480000,
    calificacion: 4.9,
    cantidadResenas: 93,
    destacado: true,
    imagenes: imagenesProducto('peluca-rizada-solange', 'Peluca Rizada Solange'),
    variantes: [
      {
        id: 'var-PRS-NEG',
        sku: 'PRS-NEG',
        precio: 480000,
        stockActual: 6,
        stockReservado: 1,
        tipoBase: 'Lace front',
        longitud: 'Extra larga',
        talla: 'Grande',
        densidad: '180%',
        color: COLORES.negroNatural,
      },
      {
        id: 'var-PRS-CHO',
        sku: 'PRS-CHO',
        precio: 480000,
        stockActual: 5,
        stockReservado: 0,
        tipoBase: 'Lace front',
        longitud: 'Extra larga',
        talla: 'Grande',
        densidad: '180%',
        color: COLORES.chocolate,
      },
      {
        id: 'var-PRS-MIEL',
        sku: 'PRS-MIEL',
        precio: 495000,
        stockActual: 3,
        stockReservado: 0,
        tipoBase: 'Lace front',
        longitud: 'Extra larga',
        talla: 'Grande',
        densidad: '180%',
        color: COLORES.miel,
      },
      {
        id: 'var-PRS-RUB',
        sku: 'PRS-RUB',
        precio: 495000,
        stockActual: 2,
        stockReservado: 1,
        tipoBase: 'Lace front',
        longitud: 'Extra larga',
        talla: 'Grande',
        densidad: '180%',
        color: COLORES.rubioArena,
      },
    ],
  },

  // --- Cuidado: sin atributos, una sola variante ---
  {
    id: 'prod-shampoo-reparador-keratina',
    nombre: 'Shampoo Reparador Keratina',
    slug: 'shampoo-reparador-keratina',
    descripcion:
      'Shampoo sin sulfatos con keratina hidrolizada para cabello natural y pelucas de fibra.',
    categoriaId: 'cat-cuidado',
    precioBase: 42000,
    calificacion: 4.6,
    cantidadResenas: 65,
    destacado: false,
    imagenes: imagenesProducto('shampoo-reparador-keratina', 'Shampoo Reparador Keratina'),
    variantes: [
      { id: 'var-SRK-250', sku: 'SRK-250', precio: 42000, stockActual: 40, stockReservado: 3 },
    ],
  },
  {
    id: 'prod-acondicionador-hidratante-argan',
    nombre: 'Acondicionador Hidratante Argán',
    slug: 'acondicionador-hidratante-argan',
    descripcion: 'Acondicionador con aceite de argán para sellar la cutícula y dar brillo.',
    categoriaId: 'cat-cuidado',
    precioBase: 45000,
    calificacion: 4.5,
    cantidadResenas: 48,
    destacado: false,
    imagenes: imagenesProducto(
      'acondicionador-hidratante-argan',
      'Acondicionador Hidratante Argán',
    ),
    variantes: [
      { id: 'var-AHA-250', sku: 'AHA-250', precio: 45000, stockActual: 35, stockReservado: 2 },
    ],
  },
  {
    id: 'prod-aceite-capilar-nutritivo',
    nombre: 'Aceite Capilar Nutritivo',
    slug: 'aceite-capilar-nutritivo',
    descripcion: 'Aceite nutritivo multiusos para puntas abiertas y control del frizz.',
    categoriaId: 'cat-cuidado',
    precioBase: 38000,
    calificacion: 4.4,
    cantidadResenas: 30,
    destacado: false,
    imagenes: imagenesProducto('aceite-capilar-nutritivo', 'Aceite Capilar Nutritivo'),
    variantes: [
      { id: 'var-ACN-60', sku: 'ACN-60', precio: 38000, stockActual: 50, stockReservado: 0 },
    ],
  },

  // --- Extensiones: varían por color y longitud ---
  {
    id: 'prod-extensiones-clip-in-seda',
    nombre: 'Extensiones Clip-in Seda',
    slug: 'extensiones-clip-in-seda',
    descripcion:
      'Set de extensiones clip-in de cabello 100% humano, fácil colocación sin necesidad de calor.',
    categoriaId: 'cat-extensiones',
    precioBase: 260000,
    calificacion: 4.6,
    cantidadResenas: 37,
    destacado: true,
    imagenes: imagenesProducto('extensiones-clip-in-seda', 'Extensiones Clip-in Seda'),
    variantes: [
      {
        id: 'var-ECS-NEG-MED',
        sku: 'ECS-NEG-MED',
        precio: 260000,
        stockActual: 12,
        stockReservado: 1,
        longitud: 'Media',
        color: COLORES.negroNatural,
      },
      {
        id: 'var-ECS-CAS-LAR',
        sku: 'ECS-CAS-LAR',
        precio: 280000,
        stockActual: 8,
        stockReservado: 0,
        longitud: 'Larga',
        color: COLORES.castanoOscuro,
      },
      {
        id: 'var-ECS-CHO-LAR',
        sku: 'ECS-CHO-LAR',
        precio: 280000,
        stockActual: 6,
        stockReservado: 1,
        longitud: 'Larga',
        color: COLORES.chocolate,
      },
    ],
  },
  {
    id: 'prod-extensiones-cortina-invisible',
    nombre: 'Extensiones Cortina Invisible',
    slug: 'extensiones-cortina-invisible',
    descripcion:
      'Extensiones tipo cortina de trama invisible, distribución uniforme en una sola pieza.',
    categoriaId: 'cat-extensiones',
    precioBase: 240000,
    calificacion: 4.5,
    cantidadResenas: 22,
    destacado: false,
    imagenes: imagenesProducto('extensiones-cortina-invisible', 'Extensiones Cortina Invisible'),
    variantes: [
      {
        id: 'var-ECI-MIEL-MED',
        sku: 'ECI-MIEL-MED',
        precio: 240000,
        stockActual: 9,
        stockReservado: 0,
        longitud: 'Media',
        color: COLORES.miel,
      },
      {
        id: 'var-ECI-RUB-LAR',
        sku: 'ECI-RUB-LAR',
        precio: 255000,
        stockActual: 5,
        stockReservado: 1,
        longitud: 'Larga',
        color: COLORES.rubioArena,
      },
    ],
  },

  // --- Accesorios: sin atributos, una sola variante ---
  {
    id: 'prod-gorro-de-malla-para-peluca',
    nombre: 'Gorro de Malla para Peluca',
    slug: 'gorro-de-malla-para-peluca',
    descripcion: 'Gorro de malla transpirable para usar como base antes de colocar la peluca.',
    categoriaId: 'cat-accesorios',
    precioBase: 18000,
    calificacion: 4.2,
    cantidadResenas: 19,
    destacado: false,
    imagenes: imagenesProducto('gorro-de-malla-para-peluca', 'Gorro de Malla para Peluca'),
    variantes: [
      { id: 'var-GMP-UNI', sku: 'GMP-UNI', precio: 18000, stockActual: 60, stockReservado: 0 },
    ],
  },
  {
    id: 'prod-peine-especial-para-pelucas',
    nombre: 'Peine Especial para Pelucas',
    slug: 'peine-especial-para-pelucas',
    descripcion:
      'Peine de cerdas anchas y espaciadas, diseñado para desenredar pelucas y extensiones sin dañarlas.',
    categoriaId: 'cat-accesorios',
    precioBase: 22000,
    calificacion: 4.3,
    cantidadResenas: 15,
    destacado: false,
    imagenes: imagenesProducto('peine-especial-para-pelucas', 'Peine Especial para Pelucas'),
    variantes: [
      { id: 'var-PEP-UNI', sku: 'PEP-UNI', precio: 22000, stockActual: 45, stockReservado: 0 },
    ],
  },
];

export const CUPONES: Cupon[] = [
  { codigo: 'INDIAROSA10', tipo: 'porcentaje', valor: 10, montoMinimo: 0 },
  { codigo: 'ROSA20', tipo: 'porcentaje', valor: 20, montoMinimo: 500000 },
  { codigo: 'ENVIOGRATIS', tipo: 'envio', valor: 0, montoMinimo: 0 },
];
